name = "spider"
main = "src/worker.js"
compatibility_date = "2024-07-31"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "spider.dev.pr/*"
zone_name = "dev.pr"

[triggers]
crons = ["*/15 * * * *"]